favicon: /img/favicon.png
# Change to your profile picture
avatar: /img/avatar.jpg
# if author sets in hexo_config, this string doesn't work
author: 'Shangjie Zhou'
author_bio: 'Undergraduate @ WHU'

since: 2020

# Top Menu 顶部菜单
# #title 为页内跳转，单页模式
# 可以选择外链或其他页面
menu:
  About: /
  Publications: /Publications
  #Blog: https://phower.me

# flink picture will load if avator link calls on error
loading_bg:
  flink: /img/profile.png

# Social Links; 社交链接，不需要的链接直接注释掉
# 可以调整显示顺序
# 图标调用 font-awesome 4.7
social:
  enable: true
social_links:
  #fab fa-twitter: /
  #fab fa-facebook-square: /
  fab fa-github: https://github.com/spaceofzsj
  #fab fa-stack-overflow: /
  fab fa-linkedin: https://www.linkedin.com/in/%E5%B0%9A%E8%8A%82-%E5%91%A8-0b2837196/
  fab fa-researchgate: https://www.researchgate.net/profile/Shangjie-Zhou
  #fab fa-weibo: /
  #fab fa-weixin: /
  #fab fa-qq: /
  fas fa-envelope: mailto:sjzhou@whu.edu.cn #E-mail
  #fas fa-rss: /  #rss

# Additional social_links，额外添加自定义链接，可显示链接名称
# name: url || icon_name
e_social:
  enable: true
e_social_links:
  Google Scholar: https://scholar.google.com/citations?hl=zh-CN&user=kBNFDgkAAAAJ || ai ai-google-scholar-square ai-lg ai-fw
  ORCID: https://orcid.org/0000-0001-9576-5011 || ai ai-orcid-square ai-lg ai-fw
  Publons: https://publons.com/researcher/5056901/shangjie-zhou/ || ai ai-publons-square ai-lg ai-fw
  arXiv: https://arxiv.org/a/zhou_s_7.html || ai ai-arxiv-square ai-lg ai-fw
  INSPIRE: https://inspirehep.net/authors/2050781?ui-citation-summary=true || ai ai-inspire-square ai-lg ai-fw

# CV download link
cv_dl:
  enable: true
  dir: https://github.com/spaceofzsj/my_cv/raw/master/zhou_cv.pdf
  description: My Detail CV.

# Box-shadow
# display box-shadow on page or not
box_shadow:
  enable: false

# CDN
# 根据需要自行添加js/css
# 自定义css可以直接写在user.styl中
CDN_USE:
  css:
    - /css/index.css
#    - https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.0/css/all.min.css # fontawesome 5
    - https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css #Academicon
  js:
    - https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js #/js/third-party/jquery.min.js
    - https://cdn.jsdelivr.net/npm/jquery-pjax@latest/jquery.pjax.min.js
    - /js/main.js